### ISSUE TITLE
dialogClass, formId property is not added,

### ISSUE THREAD

**Issue by Kshatra** [aposidelov/meteor-autoform-bootstrap-modal#1]
Line 96 in main.js:
var dialogClass = t.data['dialog-class'] !== undefined ? ' ' + t.data['dialog-class'] : '';
Should be:
var dialogClass = t.data['dialogClass'] !== undefined ? ' ' + t.data['dialogClass'] : '';

Also "formId" is not added to html, don't have enough knowledge to figure out where is the issue.

**Comment by aposidelov** [comment]
Hi Kshatra,
About dialogClass - it has been fixed, thank you.
About formId - it's used by autoform and is added to html as id attribute
